---
title: "Landmark Historical Functional Cox Regression"
author: "Andrew Leroux"
date: "`r Sys.Date()`"
output: 
    html_document:
        code_folding: hide
        number_sections: true
        toc: true
        toc_float: true
        toc_collapsed: true
    toc_depth: 4
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Landmark Historical Functional Cox Regression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE#,
  #comment = "#>"
)
```

# Introduction

This document shows how to estimate the landmark historical functional Cox regression model and extract estimated quantities of interest. The vigentte is organized in three sections. In the first section, we describe the model mathematically and provide details on the method. In the next section, we simulate data and apply the method. In the final section we show how to obtain estimated quantities of interest from the fitted model.

# The landmark historical functional Cox model (LM-HFLM)

The landmark historical functional Cox model is a extension of the Cox proportional hazards model for modeling time-to-event data (the outcome) subject to right censoring in the presence of a time-varying covariate. The model allows for the historical value of the time-varying covariate to influence an individual's risk in a way that varies over the follow-up time. This association is modeled non-parametrically using penalized regression splines. 

The landmark approach to modelling time to event data is a conditional approach whereby risk is modeled conditional on surviving up to a set of landmark times through some follow-up period which may be either short or long. Landmark models are a computationally efficient approach to approximating a Cox model where time-varying covariates and/or effects are present. In the case of the landmark historical functional Cox model, the landmark approach is an approximation of the historical functional Cox model. As a result, before describing the LM-HFLCM we first introduce the historical functional Cox model as motivation.

## Notation

Before we introduce the model we first define some necessary notation. Let $i = 1,\ldots,N$ denote individual.
Let $X_i$ be a single time invariant predictor, 
and let $Z_{i}(t_{ij})$ denote the $j^{\text{th}}$ observation of a single time varying predictor at time $t_{ij}$. We further introduce $Z_i^{\mathcal{H}}(t) = \{Z_i(s): s \leq t \}$ to denote the
history of $Z(\cdot)$ up to time $t$. It is assumed that 
$Z(\cdot)$ is a continuous and bounded stochastic process. $Z(\cdot)$ may be observed at regular or irregular intervals and possibly with error. 

Next, denote an individual's true event time as 
$T_i$, which is subject to right censoring, denoted as $C_i$. As a result of censoring, we observe $T_i^*=\min{(T_i,C_i)}$, and $d_i = 1(T_i < C_i)$, the event indicator for subject $i$. 
The observed data are then $\{T_i^*, d_i, X_i, Z_i^{\mathcal{H}}(T_i^*): 1 \leq i \leq N\}$.
Censoring time is assumed to be independent of the event time given the covariates.
For the landmark approach we also require notation related to landmark times. Specifically, we denote the collection of $L$
landmark times as $\mathbf{s} = \{s_1, \ldots, s_L\}$ and $L$ corresponding prediction window lengths $\mathbf{w} = \{w_1, \ldots, w_L \}$. 

## The historical functional Cox model

## The landmark historical functional Cox model

# LM-HFLM: Estimation


# LM-HFLM: Working with the fitted obejct

